language: node
node_js:
- node
cache: yarn
before_install:
- yarn global add serverless
script: true
#deploy:
#- provider: script
#  script: bash deploy/service.sh apiGateway
#  skip_cleanup: true
#  on:
#    repo: lekipz/shopixel-auth-api
