language: node
node_js:
- node
cache: yarn
before_install:
- yarn global add serverless
script: true
deploy:
- provider: script
  script: bash deploy/service.sh apiGateway
  skip_cleanup: true
  on:
    repo: lekipz/shopixel-api
    branch: master
- provider: script
  script: bash deploy/service.sh auth
  skip_cleanup: true
  on:
    repo: lekipz/shopixel-api
    branch: master
env:
  global:
  - secure: eSaoyyTFCPavuLTUKSm6ckBzd94vjcCOt7Uf2LPjp4rOzX6tnqVpIw63Wmv4NmZuAxkdfKovNSHLRskp0/b8l6MEPlZgXNSkMqTrwLnkDWxtwphLMcKjIgM6RTzGCKDZ10hsfxLCljHewy9GNogCRNXvmMPJzD330mZzhXivbrc4wRheql6BmDL4D/PEKA15tixjUDwvMpJ1gYSTnTbU8YovhsXMciKkuxnti72htGh8kKcQo/78uEfJAgHdkE9bSwN2F8bF2ZVlaHDFTlymwiUY5ABbl8n1ry9mDgOtXcqGbLnib1/8ZuCVVp8Z1DyOAvimqwHXTFotNyRUpkEEAADbHnTXX36x1tI6WpD2lJK8PjiteD19PMDUhCae65RynTK9yDVHRn49RcXeLjfHBc7x81tNX62QZCCzozD/k4o1YIxIf+Ld+delXaKQSQXrLg2rYbYvakVWcn1Kkg+3oSm3J1Ey7zAlYsCKkr02fwENz9dwKxsW8MmPk1WwWXDT3XKLjPTkBtdjXBVKsSNJgCycXkKXXRQjYJ3aTJxWGS8/EmPWShb7gjlGPBNiVso2iNPE4bnAPlIR2DeCWlGFg3XSobjETaKeFR809DQBtlV/YOMeQhxjGpg0K6zHbFhqxkZN1WDNyAhQ8aRTt3zVPGo+fSHctq6dqy5G7ho6eF4=
  - secure: W7DlxJjvTwb64RCkNVX05Nx610AjP2pRTMEo6HTDyIAvxmg5fxwNklWh8Nx5AU0UpIn0bvmiR4vGNAllEV+DQFcIOcvYfLlqlpTKGDtJYBQ2VaNhI6aQrW9LqzVQ0AmxB4k+KnzDpkp2BXnxccsP3KPLiOcARAi7ysI+DROFWmoRjIDK3zwLOlwlRP7E5kYngHnXygCGJjhfl1ITSglNpHYdrKAOUFAKO47rRu7AYS+640Bc4BJjnfDIQ7or7XM2SPW/uzn2qwTs9i99aoqGXWLytdRJSQcbICra2JtjuhNIXChksYznqUnWh/ORsVTYpMlsNxjNMQpmoj8RzvKyWeCVtpiSnElr4C0lGDhIBJ0Wrul4JS4ipjhRWTXRKsgeIqZRz5wzav3SoHgdQ07vxvuQvfCieq/iIB+1whCoyf2NFuXTuqOLHYBKqT3iuTcuJOZkjptL81pJPBWBxNy7/rFVruQg+iuuWxh8VLHWfcr2FJsJeVfqXjHQIerYPgSvs/q/0xhmqvwdTHdNgPDSJ8OfVgWSzWXBWpZalr5C1fjkVjRzufHCDy6KNx01KDmM9oFwxvAWD7vX//wNmnKxxafFBZo4D2e9Zbj+FbHpRUVdT2JkA6Z+k4gr6CsvMItEDmV8s8WfUdQcveQLTWHfMw80GJHJoLIlrRtjjKjqItw=
  - secure: gg5t0pplI70WtJacP5apH68pMgdx45m1n+8CkAKXO++Sqe76HdpKXL58mP6o5qqtdBVko84eQshdX4wFXOLWOKJ3wTqxq/9GNPboOd+IsBF1yWquRkkzrjZdFuL6M8bTSVQNu8dkm8PGPb/UiUqrYksBveB1SRPf3EnkFa8L5NATbZ44/kRLfNCvKgJtd/wHE81KvD5JEXF+zfcGH2SxEZjS2AKJgFo7Ik2Kk7WOU8qESwmIRBGKiHj9Zyw9lpsMBbumj8Z4qqlvc2F/bU/GLCo5C1m3yGwttfnkb+OW5nlzFJEFNqT3A5WnVO6uc+p/4mWCefVLRwRrU8MTCxiS9uetygMxp8CnPkYD9ttI0b83feuxCsx1BWA00s9DWSnJNpQm3m1EW9qejIE1V1KInCi5DDSBT9cybMlFj697YXDQ++vPizYgc6OvmGfJwFdN5fyDEkAeE+OrfJvPj41pz4ahBzgInvmp6Ag25+PG237E4TxCx24UxKyz3EMmMPjrSipyRHaWoNBPF+J31HILRnQ6+v68Z5EGbONPfR2zYs8Thhcdq16IslspdVrxduRZ/yewaFBP0dM85CzLwgjcFN7qSdUb2sxydfAjT4tYztSy1Fl3QGknJBLPjf41yvjSOpBANyHTdFNAhhESbAvz9HgUqZ9wicMbff+JSQe8ZoU=
